"""
Angular-to-React Migration Agent.

Orchestrates the full migration pipeline:
  1. Scan the Angular project for components, services, models, guards, routing, and envs.
  2. For each file, build a tailored prompt with the migration rules embedded.
  3. Call the OpenCode API endpoint to generate the React equivalent.
  4. Write the generated code to the React output directory.
  5. Produce a migration report summarising what was converted.
"""

import logging
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from .config import AgentConfig, config as default_config
from .file_scanner import (
    AngularComponent,
    AngularGuard,
    AngularModel,
    AngularProjectScan,
    AngularService,
    FileScanner,
)
from .opencode_client import OpenCodeClient
from .output_writer import OutputWriter
from .prompt_builder import PromptBuilder

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Result tracking
# ─────────────────────────────────────────────────────────────────────────────


@dataclass
class MigrationResult:
    """Tracks the outcome of migrating a single file."""
    source_file: str
    output_file: str
    file_type: str
    success: bool
    error: Optional[str] = None
    duration_s: float = 0.0


@dataclass
class MigrationRun:
    """Aggregates results from a full migration run."""
    angular_project: str
    react_output: str
    started_at: str
    finished_at: str = ""
    results: List[MigrationResult] = field(default_factory=list)

    @property
    def successes(self) -> List[MigrationResult]:
        return [r for r in self.results if r.success]

    @property
    def failures(self) -> List[MigrationResult]:
        return [r for r in self.results if not r.success]

    def to_markdown(self) -> str:
        lines = [
            "# Angular → React Migration Report",
            "",
            f"**Source project:** `{self.angular_project}`",
            f"**Output project:** `{self.react_output}`",
            f"**Started:**  {self.started_at}",
            f"**Finished:** {self.finished_at}",
            "",
            f"## Summary",
            "",
            f"| Category | Count |",
            f"|----------|-------|",
            f"| Total files migrated | {len(self.results)} |",
            f"| Successful | {len(self.successes)} |",
            f"| Failed | {len(self.failures)} |",
            "",
        ]

        if self.successes:
            lines += [
                "## Successfully Migrated Files",
                "",
                "| Source | Output | Type | Duration |",
                "|--------|--------|------|----------|",
            ]
            for r in self.successes:
                lines.append(
                    f"| `{r.source_file}` | `{r.output_file}` | {r.file_type} | {r.duration_s:.1f}s |"
                )
            lines.append("")

        if self.failures:
            lines += [
                "## Failed Migrations",
                "",
                "| Source | Type | Error |",
                "|--------|------|-------|",
            ]
            for r in self.failures:
                lines.append(
                    f"| `{r.source_file}` | {r.file_type} | {r.error} |"
                )
            lines.append("")

        lines += [
            "## Next Steps",
            "",
            "1. Run `npm install` in the React output directory.",
            "2. Review any failed migrations and convert them manually using the rules in",
            "   `ANGULAR_TO_REACT_MIGRATION_RULES.md`.",
            "3. Run `npm run dev` to start the development server.",
            "4. Run `npm run lint` to check for TypeScript/ESLint errors.",
            "5. Write or migrate unit tests using Jest + React Testing Library.",
            "",
            "---",
            "*Generated by the Angular-to-React Migration Agent*",
        ]

        return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Main agent class
# ─────────────────────────────────────────────────────────────────────────────


class MigrationAgent:
    """
    Top-level orchestrator for Angular → React migration.

    Usage::

        agent = MigrationAgent()
        report = agent.migrate(
            angular_project="/path/to/angular-salon-app",
            react_output="/path/to/react-salon-app",   # optional; uses config default
        )
        print(report.to_markdown())
    """

    def __init__(self, cfg: AgentConfig = default_config):
        self.cfg = cfg
        self._scanner = FileScanner()
        self._prompt_builder = PromptBuilder(cfg)
        self._client: Optional[OpenCodeClient] = None

    # ─────────────────────────────────────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────────────────────────────────────

    def migrate(
        self,
        angular_project: str | Path,
        react_output: Optional[str | Path] = None,
    ) -> MigrationRun:
        """
        Run the full Angular → React migration pipeline.

        Args:
            angular_project: Path to the Angular project root.
            react_output:    Path for the generated React project.
                             Defaults to config.output_dir.

        Returns:
            A MigrationRun containing per-file results and timing data.
        """
        self.cfg.validate()
        angular_project = Path(angular_project)
        output_dir = Path(react_output or self.cfg.output_dir)

        logger.info("=" * 60)
        logger.info("Angular → React Migration Agent")
        logger.info("  Source:  %s", angular_project)
        logger.info("  Output:  %s", output_dir)
        logger.info("  Model:   %s", self.cfg.model)
        logger.info("=" * 60)

        run = MigrationRun(
            angular_project=str(angular_project),
            react_output=str(output_dir),
            started_at=datetime.now().isoformat(timespec="seconds"),
        )

        # 1. Scan the Angular project
        scan = self._scanner.scan(angular_project)
        logger.info("\n%s\n", scan.summary())

        # 2. Write boilerplate (no AI needed)
        writer = OutputWriter(output_dir)
        writer.write_boilerplate()

        # 3. Migrate using AI
        system_prompt = self._prompt_builder.build_system_prompt()

        with OpenCodeClient(self.cfg) as client:
            self._client = client

            # Models first (types needed by components/services)
            for model in scan.models:
                result = self._migrate_model(model, system_prompt, writer)
                run.results.append(result)

            # Services
            for service in scan.services:
                result = self._migrate_service(service, system_prompt, writer)
                run.results.append(result)

            # Guards
            for guard in scan.guards:
                result = self._migrate_guard(guard, system_prompt, writer)
                run.results.append(result)

            # Components
            for component in scan.components:
                result = self._migrate_component(component, system_prompt, writer)
                run.results.append(result)

            # Routing (App.tsx)
            if scan.routing_file:
                result = self._migrate_routing(scan, system_prompt, writer)
                run.results.append(result)

            # Environment files
            if scan.environment_files:
                result = self._migrate_environments(scan, system_prompt, writer)
                run.results.append(result)

        run.finished_at = datetime.now().isoformat(timespec="seconds")

        # 4. Generate report
        if self.cfg.generate_report:
            report_path = writer.write_report(run.to_markdown())
            logger.info("\nMigration report written to: %s", report_path)

        successes = len(run.successes)
        failures = len(run.failures)
        logger.info(
            "\n✓ Migration complete — %d succeeded, %d failed",
            successes,
            failures,
        )

        return run

    # ─────────────────────────────────────────────────────────────────────────
    # Private migration methods
    # ─────────────────────────────────────────────────────────────────────────

    def _migrate_component(
        self,
        component: AngularComponent,
        system_prompt: str,
        writer: OutputWriter,
    ) -> MigrationResult:
        logger.info("Migrating component: %s", component.name)
        start = time.monotonic()
        try:
            user_prompt = self._prompt_builder.build_component_prompt(
                ts_source=component.ts_source,
                html_source=component.html_source,
                scss_source=component.scss_source,
                component_name=component.name,
            )
            content = self._client.complete(system_prompt, user_prompt)  # type: ignore[union-attr]
            out_path = writer.write_component(component.name, content)
            return MigrationResult(
                source_file=str(component.ts_path),
                output_file=str(out_path),
                file_type="Component",
                success=True,
                duration_s=time.monotonic() - start,
            )
        except Exception as exc:
            logger.error("  ✗ Failed to migrate %s: %s", component.name, exc)
            return MigrationResult(
                source_file=str(component.ts_path),
                output_file="",
                file_type="Component",
                success=False,
                error=str(exc),
                duration_s=time.monotonic() - start,
            )

    def _migrate_service(
        self,
        service: AngularService,
        system_prompt: str,
        writer: OutputWriter,
    ) -> MigrationResult:
        logger.info("Migrating service: %s", service.name)
        start = time.monotonic()
        try:
            user_prompt = self._prompt_builder.build_service_prompt(
                ts_source=service.ts_source,
                service_name=service.name,
            )
            content = self._client.complete(system_prompt, user_prompt)  # type: ignore[union-attr]
            out_path = writer.write_service(service.name, content)
            return MigrationResult(
                source_file=str(service.ts_path),
                output_file=str(out_path),
                file_type="Service",
                success=True,
                duration_s=time.monotonic() - start,
            )
        except Exception as exc:
            logger.error("  ✗ Failed to migrate %s: %s", service.name, exc)
            return MigrationResult(
                source_file=str(service.ts_path),
                output_file="",
                file_type="Service",
                success=False,
                error=str(exc),
                duration_s=time.monotonic() - start,
            )

    def _migrate_model(
        self,
        model: AngularModel,
        system_prompt: str,
        writer: OutputWriter,
    ) -> MigrationResult:
        logger.info("Migrating model: %s", model.name)
        start = time.monotonic()
        try:
            user_prompt = self._prompt_builder.build_model_prompt(
                ts_source=model.ts_source,
                model_name=model.name,
            )
            content = self._client.complete(system_prompt, user_prompt)  # type: ignore[union-attr]
            out_path = writer.write_type(model.name, content)
            return MigrationResult(
                source_file=str(model.ts_path),
                output_file=str(out_path),
                file_type="Model/Type",
                success=True,
                duration_s=time.monotonic() - start,
            )
        except Exception as exc:
            logger.error("  ✗ Failed to migrate %s: %s", model.name, exc)
            return MigrationResult(
                source_file=str(model.ts_path),
                output_file="",
                file_type="Model/Type",
                success=False,
                error=str(exc),
                duration_s=time.monotonic() - start,
            )

    def _migrate_guard(
        self,
        guard: AngularGuard,
        system_prompt: str,
        writer: OutputWriter,
    ) -> MigrationResult:
        logger.info("Migrating guard: %s", guard.name)
        start = time.monotonic()
        try:
            user_prompt = self._prompt_builder.build_guard_prompt(
                ts_source=guard.ts_source,
                guard_name=guard.name,
            )
            content = self._client.complete(system_prompt, user_prompt)  # type: ignore[union-attr]
            out_path = writer.write_guard(guard.name, content)
            return MigrationResult(
                source_file=str(guard.ts_path),
                output_file=str(out_path),
                file_type="Guard → ProtectedRoute",
                success=True,
                duration_s=time.monotonic() - start,
            )
        except Exception as exc:
            logger.error("  ✗ Failed to migrate %s: %s", guard.name, exc)
            return MigrationResult(
                source_file=str(guard.ts_path),
                output_file="",
                file_type="Guard → ProtectedRoute",
                success=False,
                error=str(exc),
                duration_s=time.monotonic() - start,
            )

    def _migrate_routing(
        self,
        scan: AngularProjectScan,
        system_prompt: str,
        writer: OutputWriter,
    ) -> MigrationResult:
        logger.info("Migrating routing: %s", scan.routing_file)
        start = time.monotonic()
        try:
            ts_source = scan.routing_file.read_text(encoding="utf-8")  # type: ignore[union-attr]
            context = "Components available:\n" + "\n".join(
                f"  - {c.name}" for c in scan.components
            )
            user_prompt = self._prompt_builder.build_routing_prompt(
                ts_source=ts_source,
                additional_context=context,
            )
            content = self._client.complete(system_prompt, user_prompt)  # type: ignore[union-attr]
            out_path = writer.write_app(content)
            return MigrationResult(
                source_file=str(scan.routing_file),
                output_file=str(out_path),
                file_type="Routing → App.tsx",
                success=True,
                duration_s=time.monotonic() - start,
            )
        except Exception as exc:
            logger.error("  ✗ Failed to migrate routing: %s", exc)
            return MigrationResult(
                source_file=str(scan.routing_file),
                output_file="",
                file_type="Routing → App.tsx",
                success=False,
                error=str(exc),
                duration_s=time.monotonic() - start,
            )

    def _migrate_environments(
        self,
        scan: AngularProjectScan,
        system_prompt: str,
        writer: OutputWriter,
    ) -> MigrationResult:
        env_path = scan.environment_files[0]
        logger.info("Migrating environment: %s", env_path)
        start = time.monotonic()
        try:
            ts_source = env_path.read_text(encoding="utf-8")
            user_prompt = self._prompt_builder.build_environment_prompt(ts_source)
            content = self._client.complete(system_prompt, user_prompt)  # type: ignore[union-attr]
            writer.write_env(content)
            return MigrationResult(
                source_file=str(env_path),
                output_file=".env.development / .env.production / src/config/env.ts",
                file_type="Environment",
                success=True,
                duration_s=time.monotonic() - start,
            )
        except Exception as exc:
            logger.error("  ✗ Failed to migrate environment: %s", exc)
            return MigrationResult(
                source_file=str(env_path),
                output_file="",
                file_type="Environment",
                success=False,
                error=str(exc),
                duration_s=time.monotonic() - start,
            )
